package cn.jxc.pojo;
// Generated 2018-3-14 20:32:32 by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * Backsales generated by hbm2java
 */
public class BackSales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String bsaId;
	private Customer customerId;
	private Date requestDate;
	private Employee reviewEmp;
	private ReviewStatus reviewState;
	private String backReason;

	public BackSales() {
		super();
	}

	public BackSales(String bsaId, Customer customerId, Employee reviewEmp) {
		this.bsaId = bsaId;
		this.customerId = customerId;
		this.reviewEmp = reviewEmp;
	}

	public BackSales(String bsaId, Customer customerId, Date requestDate, Employee reviewEmp, ReviewStatus reviewState,
			String backReason) {
		super();
		this.bsaId = bsaId;
		this.customerId = customerId;
		this.requestDate = requestDate;
		this.reviewEmp = reviewEmp;
		this.reviewState = reviewState;
		this.backReason = backReason;
	}

	public String getBsaId() {
		return this.bsaId;
	}

	public void setBsaId(String bsaId) {
		this.bsaId = bsaId;
	}

	public Customer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Customer customerId) {
		this.customerId = customerId;
	}

	public Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	public Employee getReviewEmp() {
		return this.reviewEmp;
	}

	public void setReviewEmp(Employee reviewEmp) {
		this.reviewEmp = reviewEmp;
	}

	public ReviewStatus getReviewState() {
		return this.reviewState;
	}

	public void setReviewState(ReviewStatus reviewState) {
		this.reviewState = reviewState;
	}

	public String getBackReason() {
		return this.backReason;
	}

	public void setBackReason(String backReason) {
		this.backReason = backReason;
	}

}
