package cn.jxc.pojo;
// Generated 2018-3-14 20:32:32 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Leavestocktype generated by hbm2java
 */
public class LeaveStockType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int lstId;
	private String lstName;
	private String lstDes;
	
	private Set<LeaveStock> leavestocks = new HashSet<LeaveStock>(0);

	public LeaveStockType() {
	}

	public LeaveStockType(int lstId, String lstName) {
		this.lstId = lstId;
		this.lstName = lstName;
	}

	public LeaveStockType(int lstId, String lstName, String lstDes, Set<LeaveStock> leavestocks) {
		this.lstId = lstId;
		this.lstName = lstName;
		this.lstDes = lstDes;
		this.leavestocks = leavestocks;
	}

	public int getLstId() {
		return this.lstId;
	}

	public void setLstId(int lstId) {
		this.lstId = lstId;
	}

	public String getLstName() {
		return this.lstName;
	}

	public void setLstName(String lstName) {
		this.lstName = lstName;
	}

	public String getLstDes() {
		return this.lstDes;
	}

	public void setLstDes(String lstDes) {
		this.lstDes = lstDes;
	}

	public Set<LeaveStock> getLeavestocks() {
		return this.leavestocks;
	}

	public void setLeavestocks(Set<LeaveStock> leavestocks) {
		this.leavestocks = leavestocks;
	}

}
