package cn.jxc.pojo;
// Generated 2018-3-14 20:32:32 by Hibernate Tools 5.2.8.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Leavestock generated by hbm2java
 */
public class LeaveStock implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String lsId; // 单号
	private Employee employee; // 出库人
	private LeaveStockType leavestocktype; // 出库类型（报损：调拨）
	private StoreHouse storehouse; // 出库仓库

	@JsonFormat(pattern = "yyyy-MM-dd")
	private Date leaveStockTime; // 出库时间
	private String upstreamNo; // 上游单号
	private String reviewEmp; // 审核人

	@JsonFormat(pattern = "yyyy-MM-dd")
	private Date reviewDate; // 审核时间
	private String reviewReason; // 审核原因
	private ReviewStatus reviewStatus;
	private String remark; // 备注

	public String getReviewEmp() {
		return reviewEmp;
	}

	public void setReviewEmp(String reviewEmp) {
		this.reviewEmp = reviewEmp;
	}

	public Date getReviewDate() {
		return reviewDate;
	}

	public void setReviewDate(Date reviewDate) {
		this.reviewDate = reviewDate;
	}

	public String getReviewReason() {
		return reviewReason;
	}

	public void setReviewReason(String reviewReason) {
		this.reviewReason = reviewReason;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public ReviewStatus getReviewStatus() {
		return reviewStatus;
	}

	public void setReviewStatus(ReviewStatus reviewStatus) {
		this.reviewStatus = reviewStatus;
	}

	private Set<LeaveStockDetail> leavestockdetails = new HashSet<LeaveStockDetail>(0);

	public LeaveStock() {
	}

	public LeaveStock(String lsId, Employee employee, LeaveStockType leavestocktype, StoreHouse storehouse,
			Date leaveStockTime, String upstreamNo) {
		this.lsId = lsId;
		this.employee = employee;
		this.leavestocktype = leavestocktype;
		this.storehouse = storehouse;
		this.leaveStockTime = leaveStockTime;
		this.upstreamNo = upstreamNo;
	}

	public LeaveStock(String lsId, Employee employee, LeaveStockType leavestocktype, StoreHouse storehouse,
			Date leaveStockTime, String upstreamNo, Set<LeaveStockDetail> leavestockdetails) {
		this.lsId = lsId;
		this.employee = employee;
		this.leavestocktype = leavestocktype;
		this.storehouse = storehouse;
		this.leaveStockTime = leaveStockTime;
		this.upstreamNo = upstreamNo;
		this.leavestockdetails = leavestockdetails;
	}

	public String getLsId() {
		return this.lsId;
	}

	public void setLsId(String lsId) {
		this.lsId = lsId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public LeaveStockType getLeavestocktype() {
		return this.leavestocktype;
	}

	public void setLeavestocktype(LeaveStockType leavestocktype) {
		this.leavestocktype = leavestocktype;
	}

	public StoreHouse getStorehouse() {
		return this.storehouse;
	}

	public void setStorehouse(StoreHouse storehouse) {
		this.storehouse = storehouse;
	}

	public Date getLeaveStockTime() {
		return this.leaveStockTime;
	}

	public void setLeaveStockTime(Date leaveStockTime) {
		this.leaveStockTime = leaveStockTime;
	}

	public String getUpstreamNo() {
		return this.upstreamNo;
	}

	public void setUpstreamNo(String upstreamNo) {
		this.upstreamNo = upstreamNo;
	}

	public Set<LeaveStockDetail> getLeavestockdetails() {
		return this.leavestockdetails;
	}

	public void setLeavestockdetails(Set<LeaveStockDetail> leavestockdetails) {
		this.leavestockdetails = leavestockdetails;
	}

}
