package cn.jxc.pojo;
// Generated 2018-3-14 20:32:32 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Producttype generated by hbm2java
 */
public class ProductType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int productTypeId;
	private String productTypeName;
	private String remark;
	
	private Set<Product> products = new HashSet<Product>(0);

	public ProductType() {
	}

	public ProductType(int productTypeId, String productTypeName) {
		this.productTypeId = productTypeId;
		this.productTypeName = productTypeName;
	}

	public ProductType(int productTypeId, String productTypeName, String remark, Set<Product> products) {
		this.productTypeId = productTypeId;
		this.productTypeName = productTypeName;
		this.remark = remark;
		this.products = products;
	}

	public int getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(int productTypeId) {
		this.productTypeId = productTypeId;
	}

	public String getProductTypeName() {
		return this.productTypeName;
	}

	public void setProductTypeName(String productTypeName) {
		this.productTypeName = productTypeName;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
