package cn.jxc.pojo;
// Generated 2018-3-14 20:32:32 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Productunit generated by hbm2java
 */
public class ProductUnit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int productUnitId;
	private String puName;
	private String puDes;
	private Employee employeeId;
	private Date createTime;
	
	private Set<Product> products = new HashSet<Product>(0);
	private Set<StockPile> stockpiles = new HashSet<StockPile>(0);

	public ProductUnit() {
	}

	public ProductUnit(int productUnitId, String puName, Employee employeeId, Date createTime) {
		this.productUnitId = productUnitId;
		this.puName = puName;
		this.employeeId = employeeId;
		this.createTime = createTime;
	}

	public ProductUnit(int productUnitId, String puName, String puDes, Employee employeeId, Date createTime, Set<Product> products,
			Set<StockPile> stockpiles) {
		this.productUnitId = productUnitId;
		this.puName = puName;
		this.puDes = puDes;
		this.employeeId = employeeId;
		this.createTime = createTime;
		this.products = products;
		this.stockpiles = stockpiles;
	}

	public int getProductUnitId() {
		return this.productUnitId;
	}

	public void setProductUnitId(int productUnitId) {
		this.productUnitId = productUnitId;
	}

	public String getPuName() {
		return this.puName;
	}

	public void setPuName(String puName) {
		this.puName = puName;
	}

	public String getPuDes() {
		return this.puDes;
	}

	public void setPuDes(String puDes) {
		this.puDes = puDes;
	}

	public Employee getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Employee employeeId) {
		this.employeeId = employeeId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	public Set<StockPile> getStockpiles() {
		return this.stockpiles;
	}

	public void setStockpiles(Set<StockPile> stockpiles) {
		this.stockpiles = stockpiles;
	}

}
